### ISSUE TITLE
uninitialized constant RSpec::Matchers (NameError)

### ISSUE THREAD

**Issue by jonatasdaniel** [kollegorna/rspec-api_helpers#6]
It's my first time using rspec-api_helpers and I got the following error when I start my server. I'm doing exactly how readme describes.

The error is:

`/usr/local/bundle/gems/rspec-api_helpers-1.0.3/lib/rspec/api_helpers/adapter/jsonapi/adapter.rb:3:in '<class:JsonApi>': uninitialized constant RSpec::Matchers (NameError)`

Am I missing something?

**Comment by vasilakisfil** [comment]
Hi, sorry not sure how I missed that I should configure my github notifications :/
Fixed in version 1.0.4, basically I had to tighten a bit the rspec dependencies (rspec-expectations was the one that was missing).
